name: Hello Github Actions 

on: 
  push: 
    branches: 
      - main 
  workflow_dispatch:  # ← ADICIONE ESTA LINHA

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps: 
      - name: Exibir mensagem no log
        run: echo "Github Actions funcionando com sucesso!"